name: Build nuitka

on:
    push:
      branches: [ 'nuitka', 'v1.2']
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
            os: [macos-13,macos-latest,windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: podman_compose.py
          # many more Nuitka options available, see action doc, but it's best
          # to use nuitka-project: options in your code, so e.g. you can make
          # a difference for macOS and create an app bundle there.
          include-package: yaml,dotenv
          include-module: _socket
          mode: onefile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} Build
          path: | # match what's created for the 3 OSes
            build/*.so
            build/*.dll
            build/*.bin
            build/*.exe
